[colors.bright]
black = "#5b6268"
blue = "#2257a0"
cyan = "#46d9ff"
green = "#4db5bd"
magenta = "#a9a1e1"
red = "#da8548"
white = "#dfdfdf"
yellow = "#ecbe7b"

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.normal]
black = "#1c1f24"
blue = "#51afef"
cyan = "#5699af"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#545A62"
yellow = "#da8548"

[colors.primary]
background = "#171717"
foreground = "#bbc2cf"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.glyph_offset]
y = 3

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
y = 7

[scrolling]
history = 2000

[window]
decorations = "buttonless"
opacity = 1

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 3
y = 1
